### ISSUE TITLE
`out` isn't technically a Coco/R keyword

### ISSUE THREAD

**Issue by alexrp** [mschoebel/cocosyntax#1]
I was a bit surprised when one of my tokens (called `out`) was highlighted as a keyword. It is a C# keyword, but not technically a Coco/R keyword.

It may be worth considering not highlighting it since it's a bit confusing why the rest of C# isn't highlighted too, then.

**Comment by mschoebel** [comment]
You are absolutely right. Thanks. I removed `out` from the list of keywords.

---

> .. the rest of C# isn't highlighted too ..

Have you tried using the special Coco/R C# mode?

![coco_cs](https://cloud.githubusercontent.com/assets/766647/3193893/7a5e9bee-ecf7-11e3-8040-f9338fe5176c.png)

**Comment by alexrp** [comment]
Didn't know that was a thing. Neat!

I'll go ahead and close this then. Thanks!
