### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by christianknu** [mschoebel/cocosyntax#4]
Hi mschoebel

I want to add Coco/R syntax highlighting to Visual Studio Code and would therefor ask for your permission, to use the .tmLanguage files in this repo for this purpose.
My intentions is to create the language support and add it to the VS Code Marketplace.
I will of course if requested refer to you and your repo in the marketplace.

Best Regards Christian!

**Comment by micalevisk** [comment]
Hey! inspired by you @christianknu I just made this another one https://github.com/micalevisk/cocosyntax-vscode and I want to publish it to VSC Marketplace as well.

I'm waiting for @mschoebel too.

**Comment by mschoebel** [comment]
Yeah, go ahead.

Took me only 5 years to respond. 🤦
